services:
  pg:
    image: postgres:17-alpine
    container_name: pg
    restart: always
    environment:
      POSTGRES_PASSWORD: qwerty123456
      POSTGRES_DB: core
    volumes:
      - pg-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  pg-data: