// SPDX-License-Identifier: MIT
pragma solidity ^0.8.29;

import {Test} from "forge-std/Test.sol";
import {MerkleProof} from "@openzeppelin/contracts/utils/cryptography/MerkleProof.sol";
import {ClearingHouse} from "../src/ClearingHouse.sol";

/// Cross-boundary known-answer test for the clearing Merkle path
///
/// The clearing path has two hand-maintained Rust<->Solidity seams, and until now each
/// was only tested Rust-vs-Rust. This pins both against a committed fixture generated by
/// `core/tests/merkle_golden_vectors.rs`:
///
///   1. Leaf preimage — the real `ClearingHouse.participantLeaf` assembly must reproduce
///      the exact keccak that Rust `hash_participant_leaf` produced.
///   2. Tree hashing — the Rust-built root and per-leaf proofs must verify under the
///      on-chain OpenZeppelin `MerkleProof` the ClearingHouse actually settles against.
///
/// The fixture's odd (5) leaf count exercises the self-pairing of a trailing node — the
/// likeliest place a second sorted-pair implementation diverges. This is the test that
/// would catch a Merkle drift the way `GuaranteeCrossBoundary` catches a claims-ABI drift.
contract ClearingMerkleCrossBoundaryTest is Test {
    string internal vectors;
    ClearingHouse internal clearingHouse;

    function setUp() public {
        // fs read of ./test/fixtures is granted in foundry.toml.
        // forge-lint: disable-next-line(unsafe-cheatcode)
        vectors = vm.readFile("test/fixtures/merkle_vectors.json");

        // `participantLeaf` binds `block.chainid` and `address(this)`, so reproduce both:
        // pin the chain id and place the ClearingHouse at the fixture's address. The leaf
        // reads no storage, so the constructor args are placeholders (core4Mica must be
        // nonzero) and etching the runtime code to the pinned address is sufficient.
        vm.chainId(vm.parseJsonUint(vectors, ".chainId"));
        address chAddr = vm.parseJsonAddress(vectors, ".clearingHouse");
        ClearingHouse deployed = new ClearingHouse(address(0xBEEF), address(0xDEAD));
        vm.etch(chAddr, address(deployed).code);
        clearingHouse = ClearingHouse(payable(chAddr));
    }

    function test_participant_leaf_and_merkle_proof_match_rust() public view {
        bytes32 root = vm.parseJsonBytes32(vectors, ".root");
        bytes32 cycleId = vm.parseJsonBytes32(vectors, ".cycleId");
        address asset = vm.parseJsonAddress(vectors, ".asset");
        address[] memory participants = vm.parseJsonAddressArray(vectors, ".participants");
        uint256[] memory amounts = vm.parseJsonUintArray(vectors, ".amounts");
        uint256[] memory roles = vm.parseJsonUintArray(vectors, ".roles");
        bytes32[] memory leaves = vm.parseJsonBytes32Array(vectors, ".leaves");

        assertEq(address(clearingHouse), vm.parseJsonAddress(vectors, ".clearingHouse"));
        assertEq(block.chainid, vm.parseJsonUint(vectors, ".chainId"));

        for (uint256 i = 0; i < participants.length; i++) {
            // Seam 1: the production leaf assembly reproduces the Rust leaf hash.
            bytes32 leaf = clearingHouse.participantLeaf(
                cycleId, asset, participants[i], amounts[i], ClearingHouse.ParticipantRole(roles[i])
            );
            assertEq(leaf, leaves[i], "participantLeaf disagrees with Rust hash_participant_leaf");

            // Seam 2: the Rust root + proof verify under the OZ MerkleProof used on-chain.
            bytes32[] memory proof = vm.parseJsonBytes32Array(vectors, string.concat(".proof", vm.toString(i)));
            assertTrue(MerkleProof.verify(proof, root, leaf), "OZ MerkleProof rejected a Rust-built proof");

            // Negative control: a one-bit-flipped leaf must not verify against the same proof.
            assertFalse(MerkleProof.verify(proof, root, leaf ^ bytes32(uint256(1))), "tampered leaf verified");
        }
    }
}
