// SPDX-License-Identifier: MIT
pragma solidity ^0.8.29;

import {Core4MicaTestBase} from "./Core4MicaTestBase.sol";
import {Guarantee} from "../src/Core4Mica.sol";
import {BLS} from "@solady/src/utils/ext/ithaca/BLS.sol";

/// Proves that a guarantee ABI-encoded and BLS-signed by the Rust core
/// (crates/rpc/tests/guarantee_golden_vectors.rs) actually verifies AND decodes on-chain.
/// This is the cross-boundary test that the Rust-only and Solidity-only suites both missed:
/// it ensures the inner claims encoding stays byte-compatible across the Rust and Solidity
/// codecs so `abi.decode(..., (Guarantee))` does not revert after the BLS check passes.
contract GuaranteeCrossBoundaryTest is Core4MicaTestBase {
    string internal vectors;

    function setUp() public override {
        super.setUp();
        // Reads the committed cross-boundary golden vectors generated by the Rust codec.
        // forge-lint: disable-next-line(unsafe-cheatcode)
        vectors = vm.readFile("test/fixtures/guarantee_vectors.json");
    }

    function _g1(string memory key) internal view returns (BLS.G1Point memory) {
        bytes32[] memory w = vm.parseJsonBytes32Array(vectors, key);
        return BLS.G1Point(w[0], w[1], w[2], w[3]);
    }

    function _g2(string memory key) internal view returns (BLS.G2Point memory) {
        bytes32[] memory w = vm.parseJsonBytes32Array(vectors, key);
        return BLS.G2Point(w[0], w[1], w[2], w[3], w[4], w[5], w[6], w[7]);
    }

    function test_rustSignedV1Guarantee_verifiesAndDecodesOnChain() public {
        BLS.G1Point memory vkey = _g1(".v1.verificationKey");
        bytes32 domain = vm.parseJsonBytes32(vectors, ".v1.domain");
        bytes memory guarantee = vm.parseJsonBytes(vectors, ".v1.guarantee");
        BLS.G2Point memory signature = _g2(".v1.signature");

        // Point version 1 at the Rust signer's key + the vector's domain.
        core4Mica.configureGuaranteeVersion(1, vkey, domain, address(0), true);

        Guarantee memory g = core4Mica.verifyAndDecodeGuarantee(guarantee, signature);

        assertEq(g.version, 1, "version");
        assertEq(g.domain, domain, "domain");
        assertEq(g.cycleId, vm.parseJsonUint(vectors, ".v1.expected.cycleId"), "cycleId");
        assertEq(g.reqId, vm.parseJsonUint(vectors, ".v1.expected.reqId"), "reqId");
        assertEq(g.client, vm.parseJsonAddress(vectors, ".v1.expected.client"), "client");
        assertEq(g.recipient, vm.parseJsonAddress(vectors, ".v1.expected.recipient"), "recipient");
        assertEq(g.amount, vm.parseJsonUint(vectors, ".v1.expected.amount"), "amount");
        assertEq(g.asset, vm.parseJsonAddress(vectors, ".v1.expected.asset"), "asset");
        assertEq(g.timestamp, vm.parseJsonUint(vectors, ".v1.expected.timestamp"), "timestamp");
    }
}
