//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.15

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "ClearingBatch")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub cycle_id: String,
    #[sea_orm(column_type = "Text")]
    pub asset_address: String,
    #[sea_orm(column_type = "Text")]
    pub batch_hash: String,
    #[sea_orm(column_type = "Text")]
    pub merkle_root: String,
    #[sea_orm(column_type = "Text")]
    pub total_net_debit: String,
    #[sea_orm(column_type = "Text")]
    pub total_net_credit: String,
    pub debtor_count: i64,
    pub creditor_count: i64,
    pub committed_at: DateTime,
    #[sea_orm(column_type = "Text", nullable)]
    pub commit_tx_hash: Option<String>,
    pub created_at: DateTime,
    pub updated_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::settlement_cycle::Entity",
        from = "Column::CycleId",
        to = "super::settlement_cycle::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    SettlementCycle,
}

impl Related<super::settlement_cycle::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SettlementCycle.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
