//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.15

use super::sea_orm_active_enums::{ParticipantCycleRole, ParticipantCycleStatus};
use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "CycleParticipantPosition")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub cycle_id: String,
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub participant: String,
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub asset_address: String,
    #[sea_orm(column_type = "Text")]
    pub gross_outgoing: String,
    #[sea_orm(column_type = "Text")]
    pub gross_incoming: String,
    #[sea_orm(column_type = "Text")]
    pub net_debit: String,
    #[sea_orm(column_type = "Text")]
    pub net_credit: String,
    pub role: ParticipantCycleRole,
    pub status: ParticipantCycleStatus,
    #[sea_orm(column_type = "Text", nullable)]
    pub settlement_tx_hash: Option<String>,
    pub created_at: DateTime,
    pub updated_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::settlement_cycle::Entity",
        from = "Column::CycleId",
        to = "super::settlement_cycle::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    SettlementCycle,
}

impl Related<super::settlement_cycle::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SettlementCycle.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
