//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.15

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "CycleExposureEdge")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub cycle_id: String,
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub payer: String,
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub payee: String,
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub asset_address: String,
    #[sea_orm(column_type = "Text")]
    pub gross_amount: String,
    #[sea_orm(column_type = "Text")]
    pub finalized_payable_amount: String,
    #[sea_orm(column_type = "Text")]
    pub disputed_amount: String,
    #[sea_orm(column_type = "Text")]
    pub cancelled_amount: String,
    pub guarantee_count: i64,
    pub created_at: DateTime,
    pub updated_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::settlement_cycle::Entity",
        from = "Column::CycleId",
        to = "super::settlement_cycle::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    SettlementCycle,
}

impl Related<super::settlement_cycle::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SettlementCycle.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
