//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.15

use super::sea_orm_active_enums::GuaranteeSettlementStatus;
use sea_orm::entity::prelude::*;
#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "Guarantee")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub tab_id: String,
    #[sea_orm(primary_key, auto_increment = false)]
    pub req_id: String,
    #[sea_orm(column_type = "Text")]
    pub from_address: String,
    #[sea_orm(column_type = "Text")]
    pub to_address: String,
    #[sea_orm(column_type = "Text")]
    pub asset_address: String,
    #[sea_orm(column_type = "Text")]
    pub value: String,
    pub version: i32,
    #[sea_orm(column_type = "Text", nullable)]
    pub cycle_id: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub guarantee_id: Option<String>,
    pub start_ts: DateTime,
    #[sea_orm(column_type = "Text", nullable)]
    pub cert: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub request: Option<String>,
    pub settlement_status: GuaranteeSettlementStatus,
    pub dispute_deadline: Option<DateTime>,
    pub finalized_at: Option<DateTime>,
    pub netted_at: Option<DateTime>,
    pub settled_at: Option<DateTime>,
    pub created_at: DateTime,
    pub updated_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::tabs::Entity",
        from = "Column::TabId",
        to = "super::tabs::Column::Id",
        on_update = "Cascade",
        on_delete = "Restrict"
    )]
    Tabs,
    #[sea_orm(
        belongs_to = "super::settlement_cycle::Entity",
        from = "Column::CycleId",
        to = "super::settlement_cycle::Column::Id",
        on_update = "Cascade",
        on_delete = "SetNull"
    )]
    SettlementCycle,
}

impl Related<super::tabs::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Tabs.def()
    }
}

impl Related<super::settlement_cycle::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SettlementCycle.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
