//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.15

use super::sea_orm_active_enums::SettlementCycleStatus;
use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "SettlementCycle")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub id: String,
    #[sea_orm(column_type = "Text")]
    pub asset_address: String,
    pub period_start: DateTime,
    pub period_end: DateTime,
    pub resolution_cutoff: DateTime,
    pub clearing_commit_deadline: DateTime,
    pub payment_submission_deadline: DateTime,
    pub payment_finality_deadline: DateTime,
    pub status: SettlementCycleStatus,
    #[sea_orm(column_type = "Text")]
    pub gross_payable_amount: String,
    #[sea_orm(column_type = "Text")]
    pub gross_receivable_amount: String,
    #[sea_orm(column_type = "Text")]
    pub net_settlement_amount: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub clearing_batch_hash: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub commit_tx_hash: Option<String>,
    pub created_at: DateTime,
    pub updated_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::clearing_batch::Entity")]
    ClearingBatch,
    #[sea_orm(has_many = "super::cycle_exposure_edge::Entity")]
    CycleExposureEdge,
    #[sea_orm(has_many = "super::cycle_participant_position::Entity")]
    CycleParticipantPosition,
    #[sea_orm(has_many = "super::guarantee::Entity")]
    Guarantee,
}

impl Related<super::clearing_batch::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ClearingBatch.def()
    }
}

impl Related<super::cycle_exposure_edge::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CycleExposureEdge.def()
    }
}

impl Related<super::cycle_participant_position::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CycleParticipantPosition.def()
    }
}

impl Related<super::guarantee::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Guarantee.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
