//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.15

use super::sea_orm_active_enums::SettlementStatus;
use super::sea_orm_active_enums::TabStatus;
use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "Tabs")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub id: String,
    #[sea_orm(column_type = "Text")]
    pub user_address: String,
    #[sea_orm(column_type = "Text")]
    pub server_address: String,
    #[sea_orm(column_type = "Text")]
    pub asset_address: String,
    pub start_ts: DateTime,
    pub status: TabStatus,
    pub settlement_status: SettlementStatus,
    #[sea_orm(column_type = "Text")]
    pub total_amount: String,
    #[sea_orm(column_type = "Text")]
    pub paid_amount: String,
    #[sea_orm(column_type = "Text")]
    pub last_req_id: String,
    pub version: i32,
    pub created_at: DateTime,
    pub updated_at: DateTime,
    pub ttl: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::guarantee::Entity")]
    Guarantee,
    #[sea_orm(
        belongs_to = "super::user::Entity",
        from = "Column::UserAddress",
        to = "super::user::Column::Address",
        on_update = "Cascade",
        on_delete = "Restrict"
    )]
    User,
}

impl Related<super::guarantee::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Guarantee.def()
    }
}

impl Related<super::user::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::User.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
