//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.15

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "UserTransaction")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub tx_id: String,
    #[sea_orm(column_type = "Text")]
    pub user_address: String,
    #[sea_orm(column_type = "Text")]
    pub recipient_address: String,
    #[sea_orm(column_type = "Text")]
    pub asset_address: String,
    #[sea_orm(column_type = "Text")]
    pub amount: String,
    #[sea_orm(column_type = "BigInteger", nullable)]
    pub block_number: Option<i64>,
    #[sea_orm(column_type = "Text", nullable)]
    pub block_hash: Option<String>,
    #[sea_orm(column_type = "Text")]
    pub status: String,
    pub confirmed_at: Option<DateTime>,
    #[sea_orm(column_type = "Text", nullable)]
    pub verified: bool,
    pub finalized: bool,
    pub failed: bool,
    pub created_at: DateTime,
    pub updated_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::user::Entity",
        from = "Column::UserAddress",
        to = "super::user::Column::Address",
        on_update = "Cascade",
        on_delete = "Restrict"
    )]
    User,
}

impl Related<super::user::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::User.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
