//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.15

use super::sea_orm_active_enums::WithdrawalStatus;
use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "Withdrawal")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub id: String,
    #[sea_orm(column_type = "Text")]
    pub user_address: String,
    #[sea_orm(column_type = "Text")]
    pub asset_address: String,
    #[sea_orm(column_type = "Text")]
    pub requested_amount: String,
    pub executed_amount: String,
    pub request_ts: DateTime,
    pub status: WithdrawalStatus,
    #[sea_orm(column_type = "BigInteger", nullable)]
    pub request_event_chain_id: Option<i64>,
    #[sea_orm(column_type = "Text", nullable)]
    pub request_event_block_hash: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub request_event_tx_hash: Option<String>,
    #[sea_orm(column_type = "BigInteger", nullable)]
    pub request_event_log_index: Option<i64>,
    #[sea_orm(column_type = "BigInteger", nullable)]
    pub cancel_event_chain_id: Option<i64>,
    #[sea_orm(column_type = "Text", nullable)]
    pub cancel_event_block_hash: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub cancel_event_tx_hash: Option<String>,
    #[sea_orm(column_type = "BigInteger", nullable)]
    pub cancel_event_log_index: Option<i64>,
    #[sea_orm(column_type = "BigInteger", nullable)]
    pub execute_event_chain_id: Option<i64>,
    #[sea_orm(column_type = "Text", nullable)]
    pub execute_event_block_hash: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub execute_event_tx_hash: Option<String>,
    #[sea_orm(column_type = "BigInteger", nullable)]
    pub execute_event_log_index: Option<i64>,
    pub created_at: DateTime,
    pub updated_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::user::Entity",
        from = "Column::UserAddress",
        to = "super::user::Column::Address",
        on_update = "Cascade",
        on_delete = "Restrict"
    )]
    User,
}

impl Related<super::user::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::User.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
