[profile.default]
src = "src"
out = "out"
libs = ["lib"]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

# Enables or disables the optimizer
optimizer = true
# The number of optimizer runs
optimizer_runs = 200
# Whether or not to use the Yul intermediate representation compilation pipeline
via_ir = true
# Override the Solidity version (this overrides `auto_detect_solc`)
solc_version = '0.8.29'
evm_version = 'prague'
[rpc_endpoints]
endpoint_url = "${HOLESKY_RPC_URL}"
# If you encounter issues, try using endpoint_url = env("ENDPOINT_URL")
