//! Cross-language golden vectors for the clearing Merkle tree
//!
//! The Rust side ([`crypto::merkle::MerkleTree`] + [`hash_participant_leaf`]) builds a
//! tree over participant leaves and emits its root, per-leaf hashes, and per-leaf
//! proofs to `contracts/test/fixtures/merkle_vectors.json`. The committed fixture is
//! consumed by `contracts/test/ClearingMerkleCrossBoundary.t.sol`, which asserts that
//! the *real* on-chain `ClearingHouse.participantLeaf` (leaf-preimage seam) and
//! OpenZeppelin `MerkleProof` (tree-hashing seam) agree with these vectors.
//!
//! These are the two hand-maintained Rust<->Solidity seams on the clearing path; until
//! now each was only tested Rust-vs-Rust. Locking them here turns any future drift
//! (a submodule bump, a hashing tweak, a leaf-layout change) into a CI failure rather
//! than a latent break of an advertised primitive.
//!
//! Do not edit the fixture by hand; regenerate with `REGEN_MERKLE_VECTORS=1`.

use std::str::FromStr;

use alloy::primitives::{Address, U256};
use core_service::evm::clearing::hash_participant_leaf;
use core_service::evm::{bytes32_hex, cycle_id_hash};
use core_service::service::netting::ClearingParticipantRole;
use crypto::merkle::{LeafHash, MerkleTree};
use serde_json::{Map, Value, json};

// Pinned so the fixture is deterministic and the Foundry side can reproduce the exact
// leaf preimages: the ClearingHouse binds `block.chainid` and `address(this)`, so the
// test sets `vm.chainId(CHAIN_ID)` and deploys the ClearingHouse at `CLEARING_HOUSE`.
const CHAIN_ID: u64 = 84532;
const CLEARING_HOUSE: &str = "0x1111111111111111111111111111111111111111";
const ASSET: &str = "0x2222222222222222222222222222222222222222";
const CYCLE_TEXT: &str = "base-sepolia:2026-04-30T00";

struct Participant {
    address: &'static str,
    amount: u64,
    role: ClearingParticipantRole,
}

/// Five participants — an odd leaf count, so the tree exercises the self-pairing of a
/// trailing node (the likeliest place a second sorted-pair implementation diverges).
fn participants() -> Vec<Participant> {
    use ClearingParticipantRole::{NetCreditor, NetDebtor};
    vec![
        Participant {
            address: "0x3333333333333333333333333333333333333333",
            amount: 10,
            role: NetDebtor,
        },
        Participant {
            address: "0x4444444444444444444444444444444444444444",
            amount: 10,
            role: NetCreditor,
        },
        Participant {
            address: "0x5555555555555555555555555555555555555555",
            amount: 3,
            role: NetDebtor,
        },
        Participant {
            address: "0x6666666666666666666666666666666666666666",
            amount: 40,
            role: NetCreditor,
        },
        Participant {
            address: "0x7777777777777777777777777777777777777777",
            amount: 7,
            role: NetDebtor,
        },
    ]
}

fn generate() -> Value {
    let clearing_house = Address::from_str(CLEARING_HOUSE).expect("clearing house address");
    let asset = Address::from_str(ASSET).expect("asset address");
    let participants = participants();

    let leaves: Vec<LeafHash> = participants
        .iter()
        .map(|p| {
            hash_participant_leaf(
                CHAIN_ID,
                clearing_house,
                CYCLE_TEXT,
                asset,
                Address::from_str(p.address).expect("participant address"),
                U256::from(p.amount),
                p.role,
            )
        })
        .collect();

    let tree = MerkleTree::from_leaves(leaves.iter().copied());

    let mut obj = Map::new();
    obj.insert(
        "_comment".into(),
        json!(
            "Generated by core/tests/merkle_golden_vectors.rs. Do not edit by hand; \
             rerun with REGEN_MERKLE_VECTORS=1."
        ),
    );
    obj.insert("chainId".into(), json!(CHAIN_ID));
    obj.insert("clearingHouse".into(), json!(CLEARING_HOUSE));
    obj.insert(
        "cycleId".into(),
        json!(bytes32_hex(cycle_id_hash(CYCLE_TEXT))),
    );
    obj.insert("asset".into(), json!(ASSET));
    obj.insert(
        "participants".into(),
        json!(participants.iter().map(|p| p.address).collect::<Vec<_>>()),
    );
    obj.insert(
        "amounts".into(),
        json!(participants.iter().map(|p| p.amount).collect::<Vec<_>>()),
    );
    obj.insert(
        "roles".into(),
        json!(
            participants
                .iter()
                .map(|p| p.role as u8)
                .collect::<Vec<_>>()
        ),
    );
    obj.insert(
        "leaves".into(),
        json!(
            leaves
                .iter()
                .map(|l| bytes32_hex(l.hash()))
                .collect::<Vec<_>>()
        ),
    );
    obj.insert("root".into(), json!(bytes32_hex(tree.root())));

    // One proof per leaf, under keys `proof0..proofN`, so the Foundry side can verify
    // every participant (parseJson has no clean nested-array form).
    for (i, leaf) in leaves.iter().enumerate() {
        let proof = tree.proof(*leaf).expect("leaf is in the tree");
        obj.insert(
            format!("proof{i}"),
            json!(proof.iter().map(|h| bytes32_hex(*h)).collect::<Vec<_>>()),
        );
    }

    Value::Object(obj)
}

fn fixture_path() -> std::path::PathBuf {
    std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("../contracts/test/fixtures/merkle_vectors.json")
}

#[test]
fn merkle_golden_vectors_match_fixture() {
    let generated_json = generate();
    let generated = serde_json::to_string_pretty(&generated_json).expect("serialize vectors");

    let path = fixture_path();
    if std::env::var("REGEN_MERKLE_VECTORS").is_ok() {
        if let Some(parent) = path.parent() {
            std::fs::create_dir_all(parent).expect("create fixtures dir");
        }
        std::fs::write(&path, format!("{generated}\n")).expect("write fixture");
        eprintln!("regenerated {}", path.display());
        return;
    }

    let committed = std::fs::read_to_string(&path).unwrap_or_else(|e| {
        panic!(
            "missing fixture {} ({e}); run REGEN_MERKLE_VECTORS=1 cargo test -p core-service \
             --test merkle_golden_vectors",
            path.display()
        )
    });

    // Compare structurally so formatting differences don't cause flakes.
    let committed_json: Value = serde_json::from_str(&committed).expect("parse committed fixture");
    assert_eq!(
        committed_json, generated_json,
        "merkle golden vectors are stale; rerun with REGEN_MERKLE_VECTORS=1 to update \
         contracts/test/fixtures/merkle_vectors.json"
    );
}
